Repository Liberty52/admin, pull requests merged in 2023-09, with the labels that each got.

#74 상품 조회시 상품 소개 이미지 조회
  src/main/java/com/liberty52/admin/service/controller/dto/ProductInfoRetrieveResponseDto.java
Labels: feature

#76 feat: MultipartFile 전송을 위한 config 추가
  src/main/java/com/liberty52/admin/global/adapter/feign/ProductServiceClient.java
  src/main/java/com/liberty52/admin/global/config/FeignImageConfig.java
Labels: 🐞 BugFix

#78 상품 소개 관리 수정
  src/main/java/com/liberty52/admin/global/adapter/feign/ProductServiceClient.java
  src/main/java/com/liberty52/admin/service/applicationservice/ProductIntroductionModifyService.java
  src/main/java/com/liberty52/admin/service/applicationservice/impl/ProductIntroductionModifyServiceImpl.java
  src/main/java/com/liberty52/admin/service/controller/ProductIntroductionModifyController.java
Labels: ✨ Feature

#80 상품 옵션 선택지 재고량 수정 기능
  src/main/java/com/liberty52/admin/service/controller/dto/CreateOptionDetailRequestDto.java
  src/main/java/com/liberty52/admin/service/controller/dto/OptionDetailModifyRequestDto.java
  src/main/java/com/liberty52/admin/service/controller/dto/ProductOptionDetailResponseDto.java
Labels: 🔨 Refactor, 🔗 API
